Curso_Django/nestorgram/nestorgram/urls.py
from django.urls import path
from django.contrib import admin

from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Curso_Django/nestorgram/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.PostsFeddView.as_view(), name='feed'),
    path('posts/new/',views.CreatePostView.as_view(), name='create'),
    path('posts/<int:post_id>/',views.PostDetailView.as_view(), name='detail'),


]

Curso_Django/nestorgram/users/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('me/profile', views.UpdateProfileUpdateView.as_view(), name='update_profile'),
    #Posts
    path('<str:username>/',views.UserDetailView.as_view() , name='detail' ),

]

Curso_Django/nestorgram/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
        integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body>
    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>
</body>

</html>

Curso_Django/nestorgram/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static 'img/instagram.png'  %}" height="45" class="d-inline-block align-top" />
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail' user.username %}">
                        {% if request.user.profile.picture %}
                        <img src="{{ request.user.profile.picture.url }}" class="rounded-circle" height="50" />
                        {% else %}
                        <img src="{% static 'img/default-profile.png' %}" height="35"
                            class="d-inline-block align-top rounded-circle" />
                        {% endif %}


                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href=" {% url 'users:logout'%} ">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

Curso_Django/nestorgram/templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>