Curso_Django/nestorgram/nestorgram/urls.py
from django.urls import path
from django.contrib import admin

from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Curso_Django/nestorgram/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.PostsFeddView.as_view(), name='feed'),
    path('posts/new/',views.CreatePostView.as_view(), name='create'),
    path('posts/<int:post_id>/',views.PostDetailView.as_view(), name='detail'),


]

Curso_Django/nestorgram/users/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('me/profile', views.UpdateProfileUpdateView.as_view(), name='update_profile'),
    #Posts
    path('<str:username>/',views.UserDetailView.as_view() , name='detail' ),

]

Curso_Django/nestorgram/users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """
        Proxy model that extends the base data with other information
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = models.ImageField(
        upload_to='users/pictures', blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):

        return self.user.username

Curso_Django/nestorgram/users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class ProfileForm(forms.ModelForm):
    website = forms.URLField(max_length=200, required=False)
    biography = forms.CharField(max_length=500, required=True)
    phone_number = forms.CharField(max_length=20, required=False)
    picture = forms.ImageField(required=True)

    class Meta:
        model = Profile
        fields = ['website', 'biography', 'phone_number', 'picture']


class SignupForm(forms.Form):

    """Sign up form."""
    username = forms.CharField(
        min_length=4,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
                'class': 'form-control',
                'required': True
            }
        )
    )
    password = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'class': 'form-control',
                'required': True
            }
        )
    )
    password_confirmation = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password Confirmation',
                'class': 'form-control',
                'required': True
            }
        )
    )

    first_name = forms.CharField(
        min_length=3,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'First name',
                'class': 'form-control',
                'required': True
            }
        )
    )
    last_name = forms.CharField(
        min_length=3,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Last name',
                'class': 'form-control',
                'required': True
            }
        )
    )

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(
            attrs={
                "placeholder": "email",
                "class": "form-control",
                'required': True
            }
        )
    )

    def clean_username(self):
        """ Username must be unique """

        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()

        if username_taken:
            raise forms.ValidationError('Username is already in use')
        return username

    def clean(self):
        """ Verify password confirmation match """
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

Curso_Django/nestorgram/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView

from django.db.utils import IntegrityError

from django.contrib.auth.models import User
from .models import Profile
from posts.models import Post
from .forms import ProfileForm, SignupForm


class UserDetailView(LoginRequiredMixin, DetailView):

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context


class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True


@login_required
def logout_view(request):
    logout(request)
    return redirect('users:login')


class LogoutView(auth_views.LogoutView):
    """Vista de logout"""
    pass


class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('posts:feed')
    """ Siempre en FormView se tiene que usar el form_valid """

    def form_valid(self, form):
        form.save()

        username = form['username'].value()
        password = form['password'].value()

        user = authenticate(
            self.request, username=username, password=password)

        login(self.request, user)

        return super().form_valid(form)


def signup(request):
    #import pdb; pdb.set_trace()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            #import pdb; pdb.set_trace()
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            login(request, user)

            return redirect('posts:feed')

    else:
        form = SignupForm()

    ctx = {
        'form': form
    }
    return render(request, 'users/signup.html', ctx)

class UpdateProfileUpdateView(LoginRequiredMixin, UpdateView):

    template_name = 'users/update_profile.html'
    model = Profile
    form_class = ProfileForm

    def get_object(self):
        """ Return user's profile """
        return self.request.user.profile

    def get_success_url(self):
        """ Return to user's profile """
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})


@login_required
def update_profile(request):
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            # print(form.cleaned_data)
            data = form.cleaned_data
            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']
            profile.save()

            url = reverse('users:detail', kwargs={
                          'username': request.user.username})
            return redirect(url)

    else:
        form = ProfileForm()

    ctx = {
        'profile': profile,
        'user': request.user,
        'form': form,
    }
    return render(request, 'users/update_profile.html', ctx)

Curso_Django/nestorgram/templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <img src="{% static 'img/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4"
                    style="max-width: 60%;">

                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
</body>

</html>

Curso_Django/nestorgram/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Animalsgram</title>
{% endblock %}

{% block container %}

<div class="container mb-5" style="margin-top: 8em;">
    <div class="row">
        <div class="col-sm-4 d-flex justify-content-center">
            <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" />
        </div>
        <div class="col-sm-8">
            <h2 style="font-weight: 100;">
                {{ user.username }}
                {% if user == request.user %}
                <a href="{% url 'users:update_profile' %}" class="ml-5 btn btn-sm btn-outline-info">
                    Edit profile
                </a>
                {% else %}
                <a href="" class="ml-5 btn btn-sm btn-primary">
                    Follow
                </a>
                {% endif %}
            </h2>
            <div class="row mt-2" style="font-size: 1.2em">
                <div class="col-sm-4">
                    <b>{{ user.profile.posts_count }}785</b> posts
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.followers }}1,401</b> followers
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.following }}491</b> following
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-sm-12">
                    <p>{{ user.profile.biography }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>
<div class="container" id="user-posts">
    <div class="row mt-3">
        {% for post in posts %}
        <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
            <a href="{% url 'posts:detail' post.id %}" class="border ">
                <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid" />
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Curso_Django/nestorgram/templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %} 
<title>Animalsgram sing in</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
    <p class='alert alert-danger' > Your username and password didn't match. Please try again</p>    
    {% endif %}
    <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control mb-2" type="text" placeholder="Username" name="username" />
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in</button>

    </form>
    <p class="mt-4">Dont have and account yet <a href="{% url 'users:signup' %}">Sign up here.</a> </p>
{% endblock %}

Curso_Django/nestorgram/templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Animalsgram sign up</title>
{% endblock %}


{% block container %}
<form action=" {% url 'users:signup' %}" method="POST">
    {% if error %}
    <p class='alert alert-danger'> {{error}} </p>
    {% endif %}

    {% csrf_token %}

    {{form.as_p}}
<!-- 
    <div class="form-group">
        <input class="form-control" type="text" placeholder="Username" name="username" required="true">
    </div>

    <div class="form-group">
        <input class="form-control" type="password" placeholder="Password" name="password" required="true">
    </div>

    <div class="form-group">
        <input class="form-control" type="password" placeholder="Password confirmation" name="password_confirmation"
            required="true">
    </div>

    <div class="form-group">
        <input class="form-control" type="text" placeholder="First Name" name="first_name" required="true">
    </div>

    <div class="form-group">
        <input class="form-control" type="text" placeholder="LastName Name" name="last_name" required="true">
    </div>

    <div class="form-group">
        <input class="form-control" type="email" placeholder="Email" name="email" required="true">
    </div -->

    <button class="btn btn-primary btn-block mt-5" type="submit">Sign in</button> 

</form>
{% endblock %}

Curso_Django/nestorgram/templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }}</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}


                <div class="media">
                    {% if profile.picture %}
                    <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else %}
                    <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b> {{error}}
                </div>
                {% endfor %}

                <hr><br>

                <div class="">
                    <label>Website</label>
                    <input class="form-control {% if form.website.errors %} is-invalid {% endif %} " name="website"
                        type="text" placeholder="Website"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}" />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                        {{error}}
                        {% endfor %}
                    </div>
                </div>

                <div class="">
                    <label>Biography</label>
                    <textarea class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography">{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>

                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                        {{ error }}
                        {% endfor%}
                    </div>
                </div>

                <div class="">
                    <label>Phone number</label>
                    <input class="form-control {% if form.phone_number.errors %} is-invalid {% endif %} "
                        name="phone_number" type="text" placeholder="Phone number"
                        value="{% if form.errors %}{{form.phone_number.value}}{% else %}{{ profile.phone_number }}{% endif %}" />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                        {{error}}
                        {% endfor %}
                    </div>
                </div>

                <button class="btn btn-primary btn-block mt-5" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}